# repos:
#   - repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.13.0  # Usa la última versión estable de mypy
#     hooks:
#       - id: mypy

  - repo: https://github.com/psf/black
    rev: 24.10.0  # Usa la última versión estable de Black
    hooks:
      - id: black
        language_version: python3.12  # Ajusta según tu versión de Python
