services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: src/app.py
    ports:
      - "5001:5001"
      - "5680:5680"
#    depends_on:
#      - redis
#      - kafka
#  redis:
#    image: redis:alpine
#    ports:
#      - "6379:6379"
#  kafka:
#    image: confluentinc/cp-kafka:latest
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0:9092
#    ports:
#      - "9092:9092"
#    depends_on:
#      - zookeeper
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - "2181:2181"
#
